In [1]:
import pandas as pd

file_path = "/content/AdventureWorks Sales.xlsx"

excel_file = pd.ExcelFile(file_path)

print(excel_file.sheet_names)

['Sales Order_data', 'Sales Territory_data', 'Sales_data', 'Reseller_data', 'Date_data', 'Product_data', 'Customer_data']

In [3]:
sales = pd.read_excel(file_path, sheet_name='Sales_data')
customers = pd.read_excel(file_path, sheet_name='Customer_data')
products = pd.read_excel(file_path, sheet_name='Product_data')
territory = pd.read_excel(file_path, sheet_name='Sales Territory_data')
dates = pd.read_excel(file_path, sheet_name='Date_data')

In [4]:
print(sales.head())

   SalesOrderLineKey  ResellerKey  CustomerKey  ProductKey  OrderDateKey  \
0           43659001          676           -1         349      20170702
1           43659002          676           -1         350      20170702
2           43659003          676           -1         351      20170702
3           43659004          676           -1         344      20170702
4           43659005          676           -1         345      20170702

   DueDateKey  ShipDateKey  SalesTerritoryKey  Order Quantity  Unit Price  \
0    20170712   20170709.0                  5               1    2024.994
1    20170712   20170709.0                  5               3    2024.994
2    20170712   20170709.0                  5               1    2024.994
3    20170712   20170709.0                  5               1    2039.994
4    20170712   20170709.0                  5               1    2039.994

   Extended Amount  Unit Price Discount Pct  Product Standard Cost  \
0         2024.994                        0              1898.0944
1         6074.982                        0              1898.0944
2         2024.994                        0              1898.0944
3         2039.994                        0              1912.1544
4         2039.994                        0              1912.1544

   Total Product Cost  Sales Amount
0           1898.0944      2024.994
1           5694.2832      6074.982
2           1898.0944      2024.994
3           1912.1544      2039.994
4           1912.1544      2039.994

In [5]:
# Merge sales + customers
df = sales.merge(customers, on='CustomerKey', how='left')

# Merge products
df = df.merge(products, on='ProductKey', how='left')

# Merge territory
df = df.merge(territory, on='SalesTerritoryKey', how='left')

print(df.shape)
df.head()

(121253, 32)

,SalesOrderLineKey,ResellerKey,CustomerKey,ProductKey,OrderDateKey,DueDateKey,ShipDateKey,SalesTerritoryKey,Order Quantity,Unit Price,...,Product,Standard Cost,Color,List Price,Model,Subcategory,Category,Region,Country,Group
0,43659001,676,-1,349,20170702,20170712,20170709.0,5,1,2024.994,...,"Mountain-100 Black, 42",1898.0944,Black,3374.99,Mountain-100,Mountain Bikes,Bikes,Southeast,United States,North America
1,43659002,676,-1,350,20170702,20170712,20170709.0,5,3,2024.994,...,"Mountain-100 Black, 44",1898.0944,Black,3374.99,Mountain-100,Mountain Bikes,Bikes,Southeast,United States,North America
2,43659003,676,-1,351,20170702,20170712,20170709.0,5,1,2024.994,...,"Mountain-100 Black, 48",1898.0944,Black,3374.99,Mountain-100,Mountain Bikes,Bikes,Southeast,United States,North America
3,43659004,676,-1,344,20170702,20170712,20170709.0,5,1,2039.994,...,"Mountain-100 Silver, 38",1912.1544,Silver,3399.99,Mountain-100,Mountain Bikes,Bikes,Southeast,United States,North America
4,43659005,676,-1,345,20170702,20170712,20170709.0,5,1,2039.994,...,"Mountain-100 Silver, 42",1912.1544,Silver,3399.99,Mountain-100,Mountain Bikes,Bikes,Southeast,United States,North America

In [6]:
# Check missing values
df.isnull().sum()

SalesOrderLineKey              0
ResellerKey                    0
CustomerKey                    0
ProductKey                     0
OrderDateKey                   0
DueDateKey                     0
ShipDateKey                 2113
SalesTerritoryKey              0
Order Quantity                 0
Unit Price                     0
Extended Amount                0
Unit Price Discount Pct        0
Product Standard Cost          0
Total Product Cost             0
Sales Amount                   0
Customer ID                    0
Customer                       0
City                           0
State-Province                 0
Country-Region                 0
Postal Code                    0
SKU                            0
Product                        0
Standard Cost                  0
Color                      34144
List Price                     0
Model                          0
Subcategory                    0
Category                       0
Region                         0
Country                        0
Group                          0
dtype: int64

In [7]:
df.isnull().sum().sort_values(ascending=False)

Color                      34144
ShipDateKey                 2113
CustomerKey                    0
SalesOrderLineKey              0
ProductKey                     0
OrderDateKey                   0
DueDateKey                     0
ResellerKey                    0
Order Quantity                 0
Unit Price                     0
Extended Amount                0
Unit Price Discount Pct        0
Product Standard Cost          0
Total Product Cost             0
Sales Amount                   0
SalesTerritoryKey              0
Customer ID                    0
Customer                       0
State-Province                 0
City                           0
Postal Code                    0
SKU                            0
Product                        0
Country-Region                 0
Standard Cost                  0
List Price                     0
Model                          0
Subcategory                    0
Category                       0
Region                         0
Country                        0
Group                          0
dtype: int64

In [8]:
df['Color'] = df['Color'].fillna('Unknown')

In [9]:
df = df.dropna(subset=['ShipDateKey'])

In [10]:
df.isnull().sum()

SalesOrderLineKey          0
ResellerKey                0
CustomerKey                0
ProductKey                 0
OrderDateKey               0
DueDateKey                 0
ShipDateKey                0
SalesTerritoryKey          0
Order Quantity             0
Unit Price                 0
Extended Amount            0
Unit Price Discount Pct    0
Product Standard Cost      0
Total Product Cost         0
Sales Amount               0
Customer ID                0
Customer                   0
City                       0
State-Province             0
Country-Region             0
Postal Code                0
SKU                        0
Product                    0
Standard Cost              0
Color                      0
List Price                 0
Model                      0
Subcategory                0
Category                   0
Region                     0
Country                    0
Group                      0
dtype: int64

In [11]:
df = df.drop_duplicates()

In [12]:
print(df.shape)

(119140, 32)

In [13]:
df.dtypes

SalesOrderLineKey            int64
ResellerKey                  int64
CustomerKey                  int64
ProductKey                   int64
OrderDateKey                 int64
DueDateKey                   int64
ShipDateKey                float64
SalesTerritoryKey            int64
Order Quantity               int64
Unit Price                 float64
Extended Amount            float64
Unit Price Discount Pct      int64
Product Standard Cost      float64
Total Product Cost         float64
Sales Amount               float64
Customer ID                 object
Customer                    object
City                        object
State-Province              object
Country-Region              object
Postal Code                 object
SKU                         object
Product                     object
Standard Cost              float64
Color                       object
List Price                 float64
Model                       object
Subcategory                 object
Category                    object
Region                      object
Country                     object
Group                       object
dtype: object

In [14]:
df['OrderDateKey'] = pd.to_datetime(df['OrderDateKey'], format='%Y%m%d')
df['DueDateKey'] = pd.to_datetime(df['DueDateKey'], format='%Y%m%d')
df['ShipDateKey'] = pd.to_datetime(df['ShipDateKey'].astype(int), format='%Y%m%d')

In [15]:
df.dtypes

SalesOrderLineKey                   int64
ResellerKey                         int64
CustomerKey                         int64
ProductKey                          int64
OrderDateKey               datetime64[ns]
DueDateKey                 datetime64[ns]
ShipDateKey                datetime64[ns]
SalesTerritoryKey                   int64
Order Quantity                      int64
Unit Price                        float64
Extended Amount                   float64
Unit Price Discount Pct             int64
Product Standard Cost             float64
Total Product Cost                float64
Sales Amount                      float64
Customer ID                        object
Customer                           object
City                               object
State-Province                     object
Country-Region                     object
Postal Code                        object
SKU                                object
Product                            object
Standard Cost                     float64
Color                              object
List Price                        float64
Model                              object
Subcategory                        object
Category                           object
Region                             object
Country                            object
Group                              object
dtype: object

In [16]:
# Remove invalid sales values
df = df[df['Sales Amount'] > 0]

# Remove invalid quantity
df = df[df['Order Quantity'] > 0]

# Remove invalid price
df = df[df['Unit Price'] > 0]

In [17]:
print(df.shape)

(119140, 32)

In [18]:
df.to_csv("clean_adventureworks.csv", index=False)